version: '3.9'
services:
    postgres:
        image: postgres:13.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - ./volumes/postgres/:/var/lib/postgresql/data/
