CREATE TABLE public.users (
    id                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ftp_user           VARCHAR NOT NULL,
    ftp_uid            INTEGER DEFAULT 33,
    ftp_gid            INTEGER DEFAULT 33,
    ftp_password       VARCHAR NOT NULL,
    ftp_dir            VARCHAR NOT NULL
);

INSERT INTO public.users (
    ftp_user,
    ftp_password,
    ftp_dir
)

VALUES (
    'bob',
    'password',
    '/home/ftp_files/bob/'
);